---
title: "Project Playground"
output: html_notebook
---


Load Packages
```{r Load Packages}
library(dplyr)
library(tidyverse)
library(ggplot2)
library(janitor)
library(lubridate)
library(tidymodels)
library(httr)
library(jsonlite)
library(sf)
library(tmap)
```


Load Data
```{r Load Data}
raw_sr_data <- read.csv("SR_data.csv") %>%
  clean_names()
```

Just ADK
```{r}
raw_adk_data <- raw_sr_data %>%
  filter(incident_adirondack_park == "true")
```

All Data Map
```{r}
raw_sr_map <- raw_sr_data[complete.cases(raw_sr_data), ] %>%
  # select(location_found_latitude,location_found_longitude) %>%
st_as_sf(coords = c("location_found_longitude", "location_found_latitude"), crs = 4326)
tmap_mode("view")
tm_shape(raw_sr_map) +
  # tm_borders() +
  # tm_shape(adk_geom_data) +
  tm_dots(size=0.02,col="red", alpha = 0.5) + tm_legend(outside = TRUE) #tm_text("Locations of Incidents in New York State that Required Ranger Assistance")
```


Take me on a date
```{r}
timey_adk_data <- na.omit(raw_adk_data) %>%
  mutate(true_start_date = paste(incident_start_date,"",format(strptime(incident_start_time, "%I:%M %p"), "%H:%M:00"))) %>%
  mutate(true_closed_date = paste(incident_closed_date,"",format(strptime(incident_closed_time, "%I:%M %p"), "%H:%M:00"))) %>%

mutate(actual_start = mdy_hms(true_start_date)) %>%
mutate(actual_closed = mdy_hms(true_closed_date)) %>%
  mutate(duration = (actual_closed-actual_start))
```


Not ADK
```{r}
raw_not_adk_data <- raw_sr_data %>%
  filter(incident_adirondack_park == "false")
```

How many single people needed rescue
```{r}
each_incident_num <- table(raw_adk_data$incident_number) %>%
  as.data.frame() %>%
  filter(Freq == 1 )
```


Counts
```{r}
count_gender <-  table(raw_adk_data['subject_gender'])
View(count_gender)
count_ages <- table(raw_adk_data['subject_age'])
View(count_ages)
count_rangers <- table(raw_adk_data['number_of_rangers_involved'])
View(count_rangers)
count_elevation <- table(raw_adk_data['location_found_elevation'])
View(count_elevation)
```


```{r}
mean(raw_adk_data$subject_age, na.rm = TRUE)
mean(raw_not_adk_data$subject_age, na.rm = TRUE)
```


Preliminary Plotting
```{r}
plot_relevant <- raw_adk_data %>%
  ggplot(aes(subject_age,location_found_elevation)) + geom_point()
```



MAPS!

ADK Region
```{r}

```


Relevant Data
```{r}
adk_geom_data <- raw_adk_data[complete.cases(raw_adk_data), ] %>%
  # select(location_found_latitude,location_found_longitude) %>%
st_as_sf(coords = c("location_found_longitude", "location_found_latitude"), crs = 4326) 
# adk_geom_data <- left_join(adk_geom_data,raw_adk_data[complete.cases(raw_adk_data), ],by=c("code")) 

tmap_mode("view")

tm_shape(adk_geom_data) +
  # tm_borders() +
  # tm_shape(adk_geom_data) +
  tm_dots(size=0.02,col="subject_age", alpha = 0.7, palette = "Spectral")

```

